### ISSUE TITLE
Wrong Transfer

### ISSUE THREAD

**Issue by zeremir** [mctrivia/DigiSweep#9]
Hi there, it looks digisweep send most of the sweeped Digibyte to you. What is going on? 
txid: a3f21df1b1f6ec36944bb86a483be7203b9084aa8abb379435676b1e180faef5
txid: 0553c09ceec7f13d304e88b243c78d7c8f57c05f32576491172ab488a0dcbf99

You should take 0.5040408 DGB as donation and send 42.6108396 DGB to my wallet address but you take 42.6108396 DGB.

If there is an error, please send my Digibyte to DFhxtfi3QPop4qZujWWBiZwC9TZF7Nu4Zq .

**Comment by mctrivia** [comment]
I will look in to this bug.  For security reasons I can only return to one of the input addresses.  Would you like me to refund to DTqrvH9VPDBnaN91Sy5VciP4qrVrJSh8VH which is where the majority of UTXO came from?

**Comment by zeremir** [comment]
Yes please, if you can refund to DTqrvH9VPDBnaN91Sy5VciP4qrVrJSh8VH, we can try again with digisweep and see if there is still a problem.

**Comment by mctrivia** [comment]
refund sent.  sorry for inconvienence.

**Comment by zeremir** [comment]
Hi there. Thanks. Refund come. But when i try digisweep again it stays at sending screen  with "Sending:
Sending send command to server.
Your private keys do not leave this machine
only signatures proving you know them."  message.

**Comment by mctrivia** [comment]
may be a problem with server you picked.

ctrl+shift+j

will open the debug window.  Try again with that open and see if any error info shows in console or network tabs.

**Comment by zeremir** [comment]
Hi there,
I am getting following error message in debug window.

"libraries.min.js:586 Uncaught TfPropertyTypeError {message: "Expected property "1" of type Satoshi, got Number 42610274.99999952", __label: undefined, __property: 1, __type: ƒ, __value: 42610274.99999952, …}"

**Comment by mctrivia** [comment]
interesting.  It is obviously a floating point error but I have not seen this before and I don't use floats in many places.  Can you expand that error so it provides all the ... values?

**Comment by mctrivia** [comment]
Just pushed an update which should fix the rounding bug.

**Comment by zeremir** [comment]
Hi there, error still exists.

"Uncaught TfPropertyTypeError {message: "Expected property "1" of type Satoshi, got Number 42610274.99999952", __label: undefined, __property: 1, __type: ƒ, __value: 42610274.99999952, …}message: "Expected property "1" of type Satoshi, got Number 42610274.99999952"__label: undefined__property: 1__type: ƒ Satoshi(value)arguments: nullcaller: nulllength: 1name: "Satoshi"prototype: {constructor: ƒ}__proto__: ƒ ()[[FunctionLocation]]: libraries.min.js:470[[Scopes]]: Scopes[4]__value: 42610274.99999952__valueTypeName: "Number"stack: "Error: Expected property "1" of type Satoshi, got Number 42610274.99999952↵    at tfSubError (https://mctrivia.github.io/DigiSweep/libraries.min.js:576:98)↵    at https://mctrivia.github.io/DigiSweep/libraries.min.js:586:63↵    at Array.every (<anonymous>)↵    at _tuple (https://mctrivia.github.io/DigiSweep/libraries.min.js:585:492)↵    at typeforce (https://mctrivia.github.io/DigiSweep/libraries.min.js:587:171)↵    at Transaction.addOutput (https://mctrivia.github.io/DigiSweep/libraries.min.js:420:65)↵    at TransactionBuilder.addOutput (https://mctrivia.github.io/DigiSweep/libraries.min.js:461:30)↵    at q.toHex (https://mctrivia.github.io/DigiSweep/libraries.min.js:803:257)↵    at https://mctrivia.github.io/DigiSweep/main.js:1308:26"__proto__: Errorconstructor: ƒ TfTypeError(type,value,valueTypeName)__proto__: Object
(anonymous) @ libraries.min.js:586
_tuple @ libraries.min.js:585
typeforce @ libraries.min.js:587
Transaction.addOutput @ libraries.min.js:420
TransactionBuilder.addOutput @ libraries.min.js:461
toHex @ libraries.min.js:803
(anonymous) @ main.js:1308
setTimeout (async)
(anonymous) @ main.js:1302
load @ main.js:1300
(anonymous) @ main.js:154
setTimeout (async)
load @ main.js:153
Promise.then (async)
(anonymous) @ main.js:142
setTimeout (async)
validate @ main.js:141
loadPage @ main.js:171"
